@startuml CU
left to right direction
skinparam packageStyle rectangle

actor Administrador


package "Gestionar comunicación y notificaciones" {

    usecase "UC5_1: Crear notificaciones" as UC5_1
    usecase "UC5_2: Eliminar notificaciones" as UC5_2
    usecase "UC5_3: Enviar notificaciones" as UC5_3

}

' Relaciones (solo actor base por herencia)

Administrador -- UC5_1
Administrador -- UC5_2
Administrador -- UC5_3

@enduml
