@startuml Gestionar_leyes
left to right direction
skinparam packageStyle rectangle

actor Especialista
actor Usuario


package "Gestionar dinámicamente leyes" {

    usecase "UC1_1: Añadir leyes" as UC1_1
    usecase "UC1_2: Editar leyes" as UC1_2
    usecase "UC1_3: Mostrar leyes" as UC1_3
    usecase "UC1_4: Eliminar leyes" as UC1_4

    usecase "UC6_1: Adaptar contenidos según nivel de conocimiento del usuario" as UC6_1
    usecase "UC6_2: Recomendar rutas de estudio personalizadas" as UC6_2
    
}

' Relaciones (solo actor base por herencia)

Especialista -- UC1_1
Especialista -- UC1_2
Usuario -- UC1_3
Especialista -- UC1_4

Especialista --> Usuario

UC1_3 ..> UC6_1 : <<include>>
UC1_3 ..> UC6_2 : <<include>>



@enduml
